spring:
  application:
    name: catalogue-rest
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@localhost:8888

  datasource:
    url: jdbc:postgresql://dpg-cqlt6q08fa8c73cgd970-a.oregon-postgres.render.com/greencity
    username: greencity_user
    password: BKgSoKwKIczChThhBz4QaKtX9ulhqaDY
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/V1__create_product_table.sql
      data-locations: classpath:db/migration/V2__insert_product_data.sql

#  flyway:
#    schemas:
#      - public
#      - catalogue
#    locations: classpath:db/migration
#    enabled: true
#    baselineOnMigrate: true

logging:
  level:
    root: INFO
    sql: info

server:
  port: 8080

